### ISSUE TITLE
SQLModel inheritance breaks sqlalchemy mutation tracking

### ISSUE THREAD

**Issue by jtpavlock** [fastapi/sqlmodel#468]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the SQLModel documentation, with the integrated search.
- [X] I already searched in Google "How to X in SQLModel" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to SQLModel but to [Pydantic](https://github.com/samuelcolvin/pydantic).
- [X] I already checked if it is not related to SQLModel but to [SQLAlchemy](https://github.com/sqlalchemy/sqlalchemy).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
#!/usr/bin/env python3

from typing import Optional, Any

import sqlalchemy
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.mutable import MutableDict, MutableSet
from sqlalchemy.orm import sessionmaker
from sqlalchemy import JSON, Column
from sqlmodel import SQLModel, Field, create_engine

Session = sessionmaker()
Base = declarative_base()


class BadTrackBase(SQLModel):
    custom: dict[str, Any] = Field(
        sa_column=Column(MutableDict.as_mutable(JSON(none_as_null=True))), default={}
    )


class BadTrack(BadTrackBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)


class Track(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    custom: dict[str, Any] = Field(
        sa_column=Column(MutableDict.as_mutable(JSON(none_as_null=True))), default={}
    )


engine = create_engine("sqlite:///:memory:")
Session.configure(bind=engine)
SQLModel.metadata.create_all(engine)
session = Session()

good_track = Track(id=1, custom={"test": "good"})
bad_track = BadTrack(id=1, custom={"test": "bad"})

session.add(good_track)
session.add(bad_track)
session.commit()

good_track.custom["test"] = "changed"
bad_track.custom["test"] = "changed"

assert good_track in session.dirty
assert bad_track in session.dirty
```

### Description

When setting a field to one of the fields supported by [sqlalchemy mutation tracking](https://docs.sqlalchemy.org/en/14/orm/extensions/mutable.html#module-sqlalchemy.ext.mutable), it seems the mutation tracking isn't working as intended. I attached the above code sample to illustrate what I mean. The assertions on the bottom of the script should pass under normal circumstance.

### Operating System

Linux

### SQLModel Version

0.08

### Python Version

3.9.13

**Comment by blerrgh** [comment]
I have the same issue in SQLModel 0.08 and it's kind of a big deal.  Is there a workaround for this besides re-assigning the entire dict i.e. `good_track.custom = {"test": changed"}` ?

**Comment by jyotirmay123** [comment]
Any update here, A big blocker before I can migrate from sqlalchemy+pydantic to sqlmodel.

**Comment by alexpotv** [comment]
Also a blocker here, commenting to stay in the loop!

**Comment by pwinged** [comment]
yep, same here, blocker.

**Comment by cch264** [comment]
Blocker here as well. Thanks for your post, saved me from burning any more time on figuring out what was going on with mutation tracking.

**Comment by tonjo** [comment]
> I have the same issue in SQLModel 0.08 and it's kind of a big deal. Is there a workaround for this besides re-assigning the entire dict i.e. `good_track.custom = {"test": changed"}` ?

Problem still present with sqlmodel 0.0.22.
Note you have to re-assign the entire dict *and commit* in order to make this work.

**Comment by YuriiMotov** [comment]
I tested it and that's what I found:

`session.dirty` behaves a bit strange, but it seems that it's not related to inheritance.
If you try mutating only one of `good_track` or `bad_track` it will work well (object will be in `session.dirty` as expected).
But after you mutate second object, first one is not in `session.dirty` anymore... But second object is IN `session.dirty`.

```py
good_track.custom["test"] = "changed first time"
assert good_track in session.dirty  # good_track is in dirty

bad_track.custom["test"] = "changed first time"
assert bad_track in session.dirty  # bad_track is in dirty

assert good_track not in session.dirty  # good_track is NOT in dirty anymore !!!
```

At the same time, mutation is handled correctly - if you commit, the object will be updated.

```py
session.commit()
session.flush()

good_track_db = session.get(Track, 1)
bad_track_db = session.get(BadTrack, 1)

assert good_track_db.custom["test"] == "changed first time"  # Mutation worked out
assert bad_track_db.custom["test"] == "changed first time"  # Mutation worked out
```

Also, it only happens if you add object and commit, then mutate it.
If you fetch objects with `session.get()`, everything works as expected.

```py
good_track_db = session.get(Track, 1)
bad_track_db = session.get(BadTrack, 1)

good_track_db.custom["test"] = "changed"
bad_track_db.custom["test"] = "changed"

assert good_track_db in session.dirty
assert bad_track_db in session.dirty
```

Full code in details:

<details>

```py
from typing import Any, Optional

from sqlalchemy import JSON, Column
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.orm import sessionmaker
from sqlmodel import Field, SQLModel, create_engine

Session = sessionmaker()


class BadTrackBase(SQLModel):
    custom: dict[str, Any] = Field(
        sa_column=Column(MutableDict.as_mutable(JSON(none_as_null=True))), default={}
    )


class BadTrack(BadTrackBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)


class Track(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    custom: dict[str, Any] = Field(
        sa_column=Column(MutableDict.as_mutable(JSON(none_as_null=True))), default={}
    )


engine = create_engine("sqlite:///:memory:")
Session.configure(bind=engine)
SQLModel.metadata.create_all(engine)

session = Session()


# ====================================================================================

good_track = Track(id=1, custom={"test": "good"})
bad_track = BadTrack(id=1, custom={"test": "bad"})

session.add(good_track)
session.add(bad_track)
session.commit()

good_track.custom["test"] = "changed first time"
assert good_track in session.dirty  # good_track is in dirty

bad_track.custom["test"] = "changed first time"
assert bad_track in session.dirty  # bad_track is in dirty

assert good_track not in session.dirty  # good_track is NOT in dirty anymore !!!

session.commit()
session.flush()

good_track_db = session.get(Track, 1)
bad_track_db = session.get(BadTrack, 1)

assert good_track_db.custom["test"] == "changed first time"  # Mutation worked out
assert bad_track_db.custom["test"] == "changed first time"  # Mutation worked out


# ====================================================================================
# But now session.dirty works fine

good_track_db.custom["test"] = "changed"
assert good_track_db in session.dirty, session.dirty

bad_track_db.custom["test"] = "changed"

assert good_track_db in session.dirty, session.dirty
assert bad_track_db in session.dirty
```
</details>

So, I think there is no issue here. The `obj in session.dirt` check works strange, but mutation is handled correctly (objects in DB are updated).

@jtpavlock, do you think we can close this issue now?

**Comment by mattgiles** [comment]
Why close this issue? The issue documents broken behavior. Things like `session.dirty` and `session.is_modified` are broken (not "weird"). That seems like an important thing for users to be aware of, and a good thing for someone to come along and fix. Both of which become less likely if the issue is closed.
